### ISSUE TITLE
Helm repo yields 404 for http head requests

### ISSUE THREAD

**Issue by klolik** [deliveryhero/helm-charts#186] opened 2021-06-22 15:24 UTC
Hey guys,
Background: trying to setup Artifactory as a proxy for https://charts.deliveryhero.io/

However HTTP HEAD requests for https://charts.deliveryhero.io/ and https://charts.deliveryhero.io/index.yaml yield 404.
Normal GET method works fine obviously. Might be blocked by CloudFlare.

This seems to make the repo not being recognised properly by Artifactory. I'd appreciate help enabling it.

Thanks,
Bart

```
$ curl https://charts.deliveryhero.io/
<!DOCTYPE html>
<html>
<head>
<title>Welcome to ChartMuseum!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to ChartMuseum!</h1>
<p>If you see this page, the ChartMuseum web server is successfully installed and
working.</p>

<p>For online documentation and support please refer to the
<a href="https://github.com/helm/chartmuseum">GitHub project</a>.<br/>

<p><em>Thank you for using ChartMuseum.</em></p>
</body>
</html>

$ curl -I https://charts.deliveryhero.io/
HTTP/2 404
date: Tue, 22 Jun 2021 15:09:23 GMT
content-type: application/json; charset=utf-8
content-length: 22
access-control-allow-credentials: true
access-control-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
access-control-allow-methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
access-control-allow-origin: https://requests.syslogistics.io
x-request-id: 493555779594cc422da0dad290eef56c
cf-cache-status: DYNAMIC
cf-request-id: 0ad5dde85e0000cc7ff98b9000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 663665ba2eedcc7f-WAW

$ curl -I https://charts.deliveryhero.io/index.yaml
HTTP/2 404
date: Tue, 22 Jun 2021 15:09:30 GMT
content-type: application/json; charset=utf-8
content-length: 22
access-control-allow-credentials: true
access-control-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
access-control-allow-methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
access-control-allow-origin: https://requests.syslogistics.io
x-request-id: b26b802303966d4527a5207cfa4cbba4
cf-cache-status: DYNAMIC
cf-request-id: 0ad5de05140000ffd0ed32a000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 663665e81f75ffd0-WAW
```

**Comment by vcmaxfield** [comment] 2021-06-22 15:28
Same issue.

**Comment by max-rocket-internet** [comment] 2021-06-22 18:26
I forget our implementation but I think it's nginx-ingress + chartmuseum + AWS s3. Perhaps @sietevecesmal knows how to allow HEAD requests so that our repo can be used behind an Artifactory proxy?

**Comment by hrishin** [comment] 2023-06-09 15:27
@max-rocket-internet any update on this issue?

**Comment by max-rocket-internet** [comment] 2023-06-12 07:52
Hi @hrishin 👋
I looked into this and it's not supported in `chartmuseum` yet. Support for HEAD was merged in https://github.com/helm/chartmuseum/pull/630 but since then there's been no new release of the project. We are running the latest released version.

The problem is, the `chartmuseum` project is currently [looking for new maintainers](https://github.com/helm/chartmuseum/issues/520). Others [are waiting](https://github.com/helm/chartmuseum/issues/688) for a release also.

**Closed** 2023-07-17 02:12 UTC
Labels: no-issue-activity
